// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jmiervtpmxagpwnpxeop.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImptaWVydnRwbXhhZ3B3bnB4ZW9wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5MDcyNjUsImV4cCI6MjA1ODQ4MzI2NX0.hgMQbt1uxRmLt1Zbqgo397AtVydtxQzuQkLp2vpHFDM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);